### ISSUE TITLE
preprocess BTCV DATASET

### ISSUE THREAD

**Issue by Yffy123456** [YtongXie/CoTr#6]
I have some questions about the preprocessing of BTCV data. I preprocessed according to nnUNet's method, but running "run_trainng.py" shows: KeyError:'bcv_32'.

**Comment by VatsalBambhania** [comment]
Hi, 
I've also got the same issue. It's showing KeyError: 'bcv_1'
Any solutions so far?

**Comment by YtongXie** [comment]
Do you use the provided nnUNet package? The nnUNet is updated quickly. Our CoTr code is matched with the provided nnUNet package. If you use the higher nnUNet version, there may be some errors.

**Comment by gaoqiong123** [comment]
可以直接把数据集改成bcv_1_0000.nii.gz这种名字，我以为遇到了这个问题，改了名字就好了
