### ISSUE TITLE
RuntimeError: The size of tensor a (6) must match the size of tensor b (5) at non-singleton dimension 4

### ISSUE THREAD

**Issue by VatsalBambhania** [YtongXie/CoTr#7]
Hi,
I'm trying to train the CoTr model on Hippocampus dataset that I downloaded from http://medicaldecathlon.com/
However, I'm getting the error that the size of the tensors when performing the in skip connection operation doesn't match. 

![image](https://github.com/YtongXie/CoTr/assets/70808460/f6c53de6-665f-44cc-b143-3af218129514)

The error is basically somewhere in the CoTr/network_architecture/ResTranUnet.py line 156
x = x + skip2

I tried to solve the issue but I don't fully understand the source of the error. 
Any help will be really appreciated

Thank you

**Comment by YtongXie** [comment]
Could you print the shape of x and skip2？
